version: "3.7"
services:
  db:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: 'gallery'
      MYSQL_PASSWORD: 'gallery'
      MYSQL_DATABASE: 'image_gallery'
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - ./docker/data:/docker-entrypoint-initdb.d
    networks:
      - backend

  # Api Service
  api:
    build:
      context: ./
      dockerfile: ./docker/build/golang/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./app:/go:rw
    networks:
      - backend

networks:
  backend:
    driver: "bridge"