version: "3.7"
services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: image_gallery
      MYSQL_USER: root
    volumes:
      - ./docker/etc/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/etc/mysql/user.cnf:/tmp/user.cnf
      - ./docker/data:/data
    networks:
      - backend

  # Api Service
  api:
    build:
      context: ./
      dockerfile: ./docker/build/golang/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./app:/go:rw
    networks:
      - backend

networks:
  backend:
    driver: "bridge"