version: "3.7"
services:
  # Api Service
  api:
    depends_on:
      - db
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
    restart: unless-stopped
    networks: 
      - backend
    volumes:
      - ./:/go:rw
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_HOST: $MYSQL_HOST
      MYSQL_PORT: $MYSQL_PORT
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
      MYSQL_USER: $MYSQL_USER
    networks:
      - backend

networks:
  backend:
    driver: bridge