version: "3.7"
services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: image_gallery
      MYSQL_USER: root
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    networks:
      - backend
  # Api Service
  api:
    depends_on:
      - db
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
    volumes:
      - ./:/go:rw
    networks:
      - backend


networks:
  backend:
    driver: "bridge"